" Plugin manager
call plug#begin('~/.vim/plugged')

Plug 'PProvost/vim-ps1'
Plug 'scrooloose/nerdcommenter'
Plug 'saltstack/salt-vim'
Plug 'flazz/vim-colorschemes'

call plug#end()


" Syntax Highlighting
syntax on 
colorscheme Chasing_Logic

filetype plugin indent on 
set encoding=utf-8
set tabstop=4
set shiftwidth=4
set smarttab

" Change escape sequence to  
inoremap jk <ESC>
xnoremap jk <ESC>

set timeout timeoutlen=200 ttimeoutlen=100

let mapleader = "\<Space>"

" Open file
nnoremap <Leader>w :w<CR>
