" Plugin manager

call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdcommenter'
Plug 'haya14busa/incsearch.vim'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/incsearch-easymotion.vim'
Plug 'mbbill/undotree'
Plug 'scrooloose/nerdtree'

call plug#end()

set timeout timeoutlen=200 ttimeoutlen=100

let mapleader = "\<Space>"

" Change escape sequence to  
inoremap jk <ESC>
xnoremap jk <ESC>

" Change window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Syntax Highlighting
syntax on 
colorscheme Chasing_Logic

filetype plugin indent on 
set encoding=utf-8
set tabstop=4
set shiftwidth=4
set smarttab

" Set Statusline
set laststatus=2
set statusline=%.20f
set statusline+=\ %l/%L

" Undofile
set undofile
set undodir=~/.vim/undodir
if has('persistent_undo')
    set rtp+=~/configit/vim/modules/undotree
    nnoremap <silent> <Space>u :UndotreeToggle<CR>
    let g:undotree_SetFocusWhenToggle = 1
    set undofile
    set undodir=~/.undodir/
    set undolevels=1000
    set undoreload=10000
endif

" Undotree
nnoremap <C-u> :UndotreeToggle<cr>

" undotree window width
if !exists('g:undotree_SplitWidth')
    let g:undotree_SplitWidth = 30
endif

" NerdCommenter settings
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
map <leader>/ <plug>NERDCommenterToggle

" NerdTree settings
map <C-n> :NERDTreeToggle<cr>
" Close vim if NerdTree is only buffer
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif


" Incsearch settings
map /  <Plug>(incsearch-easymotion-/)
map ?  <Plug>(incsearch-easymotion-?)
map g/ <Plug>(incsearch-easymotion-stay)

set hlsearch
let g:incsearch#auto_nohlsearch = 1
map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
map #  <Plug>(incsearch-nohl-#)
map g* <Plug>(incsearch-nohl-g*)
map g# <Plug>(incsearch-nohl-g#)

let g:incsearch#magic = '\v'

augroup incsearch-keymap
    autocmd!
    autocmd VimEnter call s:incsearch_keymap()
augroup END
function! s:incsearch_keymap()
    IncSearchNoreMap <C-n> <Over>(incsearch-next)
    IncSearchNoreMap <C-p> <Over>(incsearch-prev)
    IncSearchNoreMap <C-f> <Over>(incsearch-scroll-f)
    IncSearchNoreMap <C-b> <Over>(incsearch-scroll-b)
endfunction

" Clear trailing whitespace in selected file types on save
autocmd BufWritePre *.py,*.js,*.hs,*.html,*.css,*.scss :%s/\s\+$//e
