
# Shell Aliases
alias sup='sudo $(fc -ln -1)'
alias sudo='sudo '
alias pubkey="cat ~/.ssh/id_rsa.pub | xsel --clipboard | echo '=> Public key copied to pasteboard.'"
alias open='xdg-open'
alias todo='nvim ~/notes/todo.org'
# Output and copy to clipboard without trailing newline
alias clip='xargs echo -n | tee >(xsel --clipboard)'
# Update all canvas files
alias canvas="python3 $HOME/projects/canvas_downloader/main.py --config $HOME/projects/canvas_downloader/config.yaml"

# cd aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# create parent directories automatically
alias mkdir='mkdir -pv'

#safety net
alias rm='rm -I --preserve-root'

# Autojump

source /etc/profile.d/autojump.sh

sha() {
    sha256sum $1 | cut -d' ' -f1 | tee >(tr -d '[:space:]' | xsel --clipboard) 
}

# Edit with nvim or sudo edit with nvim
source ~/scripts/permissions.sh
nv() {
    if [ ! -n "$1" ]; then
        nvim
        return
    fi

	if [ ! -a "$1" ] && can_write $(dirname $1); then
		nvim $1
		return
	else
		sudoedit $1
		return
	fi

	if can_edit $1; then
		nvim $1
		return
	else
		sudoedit $1
		return
	fi
}


# Config editing aliases

alias ez='nvim ~/.zshrc && source ~/.zshrc'
alias ev='nvim ~/.SpaceVim.d/init.vim'
alias et='nvim ~/.tmux.conf'

# Extract alias
alias extract='dtrx'

# Determine ls type

if ls --color -d . > /dev/null 2>&1; then
	alias ls=' ls --color=auto'
elif ls -G -d . > /dev/null 2>&1; then
	alias ls=' ls -G'
fi

# Git Aliases

alias ga='git add'
alias gc='git commit -m'
alias gl='git pull --prune'
alias gp='git push origin HEAD'
alias gd='git diff'
alias gco='git checkout'
alias gcb='git copy-branch-name'
alias gcl='git clean -dix'
alias gb='git branch'
alias gs='git status -sb'
alias gac='git add -A && git commit -m'

# Completion
bindkey '^Xr' most-recent-file

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
autoload -U compinit && compinit

# History

HISTFILE=$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_ignore_space
setopt hist_verify
setopt share_history
setopt hist_ignore_dups

# Directory Options

setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
setopt extended_glob

# Define Word Endings

WORDCHARS='*?+[]~=&;!#$%^(){}<>'

# Vim keybindings
bindkey -e

# Terminal Colors

autoload -U colors
colors

TC='\e['
Rst="${TC}0m"     # Reset all coloring and style
Black="${TC}30m";
Red="${TC}31m";
Green="${TC}32m";
Yellow="${TC}33m";
Blue="${TC}35m";
Purple="${TC}35m";
Cyan="${TC}36m";
White="${TC}37m";

# Theme

source "$HOME/.dotfiles/zsh/zsh-theme.zsh"

# Standard Configs

export LANG=en_US.UTF-8
export TERM=screen-256color
export EDITOR=nvim
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR
export WINEPREFIX=$HOME/win32
export WINEARCH=win32
export VIRTUAL_ENV_DISABLE_PROMPT=1
export RUST_SRC_PATH=/home/ccheek/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src

